apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJiYWxhamkzNjQ5MCIsInBhc3N3b3JkIjoiQmFsYWppQDI4MCIsImVtYWlsIjoic2l2YWJhbGFqaS4yODBAZ21haWwuY29tIiwiYXV0aCI6IlltRnNZV3BwTXpZME9UQTZRbUZzWVdwcFFESTRNQT09In19fQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: regcred
type: kubernetes.io/dockerconfigjson