apiVersion: v1
kind: Service
metadata:
  name: petclinic-service
spec:
  type: LoadBalancer
  selector:
    app: petclinic
  ports:
    - protocol: TCP
      port: 8080       # Exposes port 80 on the external IP
      targetPort: 8080 # Forwards traffic to port 80 on the pod