name: "building petclinic spring boot application and deploying on kubernenets"

on: 
  push:
   branches:
     - master
  workflow_dispatch:
    
jobs:
  build:
   name: building the application
   runs-on: ubuntu-latest
   steps:
     - name: checkout
       uses: actions/checkout@v4
       with:
         ref: master
    
     - name: setup java 
       uses: actions/setup-java@v3
       with:
         distribution: 'temurin'
         java-version: '17'
     
     - name: building the application 
       run: mvn clean package -DskipTests

     - name: upload an artifact
       uses: actions/upload-artifact@v4
       with:
         name: artifact
         path: target/*.war

  docker_build:
    name: creating image 
    runs-on: ubuntu-latest
    needs: build
    steps:
     
     - name: checkout
       uses: actions/checkout@v4
       with:
         ref: master

     - name: download the artifacts
       uses: actions/download-artifact@v4
       with: 
         name: artifact


     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v3

     - name: listing out the files
       run: ls -l 

     - name: Log in to Docker Hub
       uses: docker/login-action@v3
       with:
        username: balaji36490
        password: Balaji@280

     - name: Build Docker image
       run: docker buildx build -t balaji36490/petclinic:latest --load .

     - name: Push Docker image
       run: docker push balaji36490/petclinic:latest
      
          
