name: "building petclinic spring boot application and deploying on kubernenets"

on: 
  push:
   branches:
     - master
  workflow_dispatch:
    
jobs:
  build:
   name: building the application
   runs-on: ubuntu-latest
   steps:
     - name: checkout
       uses: actions/checkout@v4
       with:
         ref: master
    
     - name: setup java 
       uses: actions/setup-java@v3
       with:
         distribution: 'temurin'
         java-version: '17'
     
     - name: building the application 
       run: mvn clean package -DskipTests

     - name: seeing the listed files
       run: |
         pwd
         ls -l
          
